/**
 * Product type
 * ----------------
 * Represents a product row in the database.
 *
 * IMPORTANT:
 * - `createdAt` and `updatedAt` are stored as UNIX timestamps
 * - Unit: milliseconds since epoch (Date.now())
 * - Convert to `Date` ONLY when displaying in the UI
 */
export type Product = {
  id: number;
  name: string;
  price: number;
  image?: string | null;

  /** UNIX timestamp (milliseconds) */
  createdAt: number;

  /** UNIX timestamp (milliseconds) */
  updatedAt: number;
};

/**
 * NewProduct type
 * ----------------
 * Represents the required data for creating a new product.
 *
 * NOTE:
 * - `createdAt` and `updatedAt` are auto-generated by the database
 */
export type NewProduct = {
  name: string;
  price: number;
  image?: string | null;
};

/* ---------------------------------------------
   Sales / POS types
----------------------------------------------*/

/**
 * Sale type
 * ----------------
 * Represents a sale row in the database.
 *
 * IMPORTANT:
 * - Timestamps are stored as numbers (milliseconds)
 * - Never store `Date` objects in the database layer
 */
export type Sale = {
  id: number;
  total: number;
  paymentMethod?: string | null;
  note?: string | null;

/** Optional human-readable sale number (e.g., daily reset) */
  saleNumber?: number;

  /** UNIX timestamp (milliseconds) */
  createdAt: number;

  /** UNIX timestamp (milliseconds) */
  updatedAt: number;
};

/**
 * NewSale type
 * ----------------
 * Represents the required data for creating a new sale.
 *
 * NOTE:
 * - `createdAt` and `updatedAt` are automatically set by the database
 */
export type NewSale = {
  total: number;
  paymentMethod?: string | null;
  note?: string | null;
};

/**
 * SaleItem type
 * ----------------
 * Represents a sale item row in the database.
 */
export type SaleItem = {
  id: number;
  saleId: number;
  productId: number;
  quantity: number;
  unitPrice: number;
  subtotal: number;
};

/**
 * NewSaleItem type
 * ----------------
 * Represents the required data for creating a new sale item.
 *
 * NOTE:
 * - `saleId` is injected by the repository during checkout
 */
export type NewSaleItem = {
  productId: number;
  quantity: number;
  unitPrice: number;
  subtotal: number;
};

/* ---------------------------------------------
   Joined type for displaying sales with items
----------------------------------------------*/

/**
 * SaleWithItems type
 * ----------------
 * Used for dashboards, reports, and debugging screens.
 *
 * Combines:
 * - Sale (with numeric timestamps)
 * - Its associated line items
 */
export type SaleWithItems = Sale & {
  items: {
    productId: number;
    productName: string;
    quantity: number;
    subtotal: number;
  }[];
   saleNumber?: number; // optional number
};
